### ISSUE TITLE
open ./images/*.ditar:  no such file or directory

### ISSUE THREAD

**Issue by ehsanmostajeran** [cilium-team/cilium#1]
Hi, thanks for repo.
I get an error when using Vagrantfile. 

`==> node1: Setting up openvswitch-switch (2.4.0-1) ...
==> node1:  * Inserting openvswitch module
==> node1:  * /etc/openvswitch/conf.db does not exist
==> node1:  * Creating empty database /etc/openvswitch/conf.db
==> node1:  * Starting ovsdb-server
==> node1:  * Configuring Open vSwitch system IDs
==> node1:  * Starting ovs-vswitchd
==> node1:  * Enabling remote OVSDB managers
==> node1: Processing triggers for ureadahead (0.100.0-16) ...
==> node1: Processing triggers for man-db (2.6.7.1-1) ...
==> node1: docker stop/waiting
==> node1: docker start/running, process 5456
==> node1: Importing ./images/*.ditar...
==> node1: open ./images/*.ditar: no such file or directory`

**Comment by aanm** [comment]
Hi, which configuration are you following? https://github.com/cilium-team/cilium#how-to-run-cilium

**Comment by ehsanmostajeran** [comment]
Hi, yes from the link above. I got this error when I tried to use Vagrantfile.

**Comment by aanm** [comment]
But which of the 3 setups you tried?

**Comment by ehsanmostajeran** [comment]
I tried to bring up Cilium platform using Vagrantfile. There are images that must be pulled on vagrant nodes to run Cilium components. I guess the folder included those images is not defined in Vagrantfile or it is empty.

**Comment by aanm** [comment]
There isn't a single line that tells you to run the vagrant as standalone. You should always use the `entrypoint.sh` as described on the README.md.

I'm going to close this issue. If you have questions please make them here that I'll answer.
